from tkinter import *
root=Tk()
root.geometry("644x700")
root.wm_iconbitmap("calculator.ico")
root.title("Calculator")

scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvariable=scvalue,font="lucida 20 bold")
screen.pack(fill=X,ipadx=8,pady=10,padx=10)

def click(event):
    text=event.widget.cget("text")
    print(text)
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(screen.get())
            scvalue.set(value)
            screen.update()
    elif text=="C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()

f1=Frame(root,bg="grey")
b1=Button(f1,text="9",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="8",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="7",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
f1.pack()

f1=Frame(root,bg="grey")
b1=Button(f1,text="6",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="5",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="4",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
f1.pack()

f1=Frame(root,bg="grey")
b1=Button(f1,text="3",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="2",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="1",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
f1.pack()

f1=Frame(root,bg="grey")
b1=Button(f1,text="0",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="*",font="lucida 10 bold",padx=11,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="/",font="lucida 10 bold",padx=11,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
f1.pack()

f1=Frame(root,bg="grey")
b1=Button(f1,text="+",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="-",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="=",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
f1.pack()

f1=Frame(root,bg="grey")
b1=Button(f1,text="C",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text="00",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
b1=Button(f1,text=".",font="lucida 10 bold",padx=10,pady=10)
b1.pack(side=LEFT,fill=X)
b1.bind("<Button-1>",click)
f1.pack()
root.mainloop()